### ISSUE TITLE
Nedostaje prijevod za podizdavace

### ISSUE THREAD

**Issue by schlos** [datagovhr/data.gov.hr#2]
Nedostaje prijevod za podizdavace

```
<span class="" data-placement="right">
                Include sub-publishers
              </span>
```

Screenshot:
https://qsnapnet.com/snaps/pj2sdxgolpx2yb9

**Comment by datagovhr** [comment]
![bez naslova](https://cloud.githubusercontent.com/assets/11025655/6737970/6b8cad7c-ce6f-11e4-989b-f45d4ba7c816.png)

nekidan smo to bas primijetili... to se desi kad kliknes?

**Comment by schlos** [comment]
Da, kad pokusas vidjeti podizdavace ("Ukljuci podizadavce")

**Comment by datagovhr** [comment]
![bez naslova](https://cloud.githubusercontent.com/assets/11025655/6738205/c64ae7aa-ce70-11e4-9507-800008198939.png)

hm... nama i dalje se vidi ok... ?

**Comment by VladimirZD** [comment]
Hvala na prijavi, sada se vidi, jer je ispravljeno. :)
